version: '3'
services:
  ingress:
    build: ./ingress/
    ports:
      - 443:443
    image: ingress
    volumes:
      - /etc/ssl:/etc/ssl
      - static:/static
      - media:/media
    restart: on-failure
    depends_on:
      - api
      - app

  api_db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'

  api:
    image: api
    build: ./api
    volumes:
      - static:/static/
      - media:/app/media/
    environment:
      SECRET_KEY: '${SECRET_KEY}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '5432'
      DB_HOST: api_db
      ADMIN_USER: '${ADMIN_USER}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      BSC_CHAIN_ID: '${BSC_CHAIN_ID}'
      BSC_START_BLOCK: '${BSC_START_BLOCK}'
      ETH_CHAIN_ID: '${ETH_CHAIN_ID}'
      ETH_START_BLOCK: '${ETH_START_BLOCK}'
      POLYGON_CHAIN_ID: '${POLYGON_CHAIN_ID}'
      POLYGON_START_BLOCK: '${POLYGON_START_BLOCK}'
    restart: on-failure
    depends_on:
      - api_db

  bsc_indexer:
    image: api
    build: ./api
    volumes:
      - media:/app/media/
    environment:
      SECRET_KEY: '${SECRET_KEY}'
      UPSTREAM: '${BSC_UPSTREAM}'
      TOKEN_ABI_FILENAME: 'erc721-abi.json'
      TOKEN_ADDRESS: '${BSC_TOKEN_ADDRESS}'
      BRIDGE_ADDRESS: '${BSC_BRIDGE_ADDRESS}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '5432'
      DB_HOST: api_db
    command: python3 indexer_worker.py
    restart: on-failure
    depends_on:
      - api_db

  polygon_indexer:
    image: api
    build: ./api
    environment:
      SECRET_KEY: '${SECRET_KEY}'
      UPSTREAM: '${POLYGON_UPSTREAM}'
      TOKEN_ABI_FILENAME: 'erc721-abi.json'
      TOKEN_ADDRESS: '${POLYGON_TOKEN_ADDRESS}'
      BRIDGE_ADDRESS: '${POLYGON_BRIDGE_ADDRESS}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '5432'
      DB_HOST: api_db
    command: python3 indexer_worker.py
    restart: on-failure
    depends_on:
      - api_db

  eth_indexer:
    image: api
    build: ./api
    environment:
      SECRET_KEY: '${SECRET_KEY}'
      UPSTREAM: '${ETH_UPSTREAM}'
      TOKEN_ABI_FILENAME: 'erc721-abi.json'
      TOKEN_ADDRESS: '${ETH_TOKEN_ADDRESS}'
      BRIDGE_ADDRESS: '${ETH_BRIDGE_ADDRESS}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '5432'
      DB_HOST: api_db
    command: python3 indexer_worker.py
    restart: on-failure
    depends_on:
      - api_db

  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        REACT_APP_API_HOST: '${REACT_APP_API_HOST}'
    restart: on-failure

volumes:
  static:
  db:
  media:
